Chapter 13 Exercises

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from ISLP import load_data

from scipy.stats import \
    (ttest_1samp,
     ttest_rel,
     ttest_ind,
     t as t_dbn)
from statsmodels.stats.multicomp import \
     pairwise_tukeyhsd
from statsmodels.stats.multitest import \
     multipletests as mult_test

print("Done")

Done


8

In [17]:
rng = np.random.default_rng(1)
n, m = 20, 100
X = rng.normal(size=(n, m))

A

In [18]:
p_values = np.empty(100)
for i in range(100):
   p_values[i] = ttest_1samp(X[:,i], 0).pvalue


In [23]:
p_values

array([5.38801264e-02, 2.02572586e-01, 8.56777131e-01, 6.19586963e-01,
       4.66053738e-01, 8.99407380e-01, 6.54314667e-01, 2.51122603e-01,
       2.44481627e-01, 7.79596231e-02, 2.23867120e-01, 1.18753604e-01,
       9.16142811e-01, 2.59936463e-01, 8.06613377e-04, 1.68754852e-01,
       2.24102132e-01, 4.66990660e-01, 9.17115858e-01, 3.24539642e-01,
       7.55006259e-02, 2.26051291e-01, 3.71947638e-01, 5.50363076e-01,
       5.06617712e-01, 1.77938985e-01, 4.95026920e-01, 3.55394796e-02,
       7.86809820e-01, 3.91440181e-01, 5.97764221e-01, 4.93905898e-01,
       9.09168824e-01, 9.03392460e-01, 7.69811614e-01, 8.79382732e-02,
       2.98052636e-01, 3.34499336e-01, 5.86508435e-01, 2.29332821e-02,
       9.69657768e-02, 8.52533463e-01, 1.27961775e-01, 5.23975261e-01,
       9.55121024e-03, 8.74269694e-01, 5.35129668e-01, 3.81090333e-01,
       4.45682897e-01, 3.93321809e-01, 6.56456680e-02, 1.72261062e-01,
       5.53309877e-01, 8.77870665e-01, 7.67945550e-01, 5.28061448e-01,
      

In [19]:
reject = np.empty(100)
for v in range(100):
    if p_values[v] < 0.05:
        reject[v] = 1
    else:
        reject[v] = 0

reject

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

B

In [20]:
np.sum(reject)

4.0

We reject 4 hypothesis

C

In [25]:
mult_test(p_values, method = "holm", alpha=0.05)

(array([False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False]),
 array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 0.08066134

We cannot reject any of the hypothesis

D

In [26]:
qvalues = mult_test(p_values, method = "fdr_bh")[1]
qvalues[:10]

array([0.7535043 , 0.7535043 , 0.92637965, 0.85875772, 0.84037158,
       0.92637965, 0.87241956, 0.78475813, 0.78475813, 0.7535043 ])

In [27]:
(qvalues <= 0.05).sum()

0

We still cannot reject any of the null hypothesis, which is what we expect based off the simulated data